spring:
  datasource:
    url: jdbc:mysql://b7uitcr8kqgx29popgiz-mysql.services.clever-cloud.com:3306/b7uitcr8kqgx29popgiz?useSSL=false&serverTimezone=UTC
    username: u3yfu7iunsu5t08n
    password: lE4fGvO7kiAFZ6x9PYxq
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: true
  servlet:
    multipart:
      max-file-size: 5MB
media:
  location: mediafiles