spring:
  datasource:
    url: jdbc:mysql://aws.connect.psdb.cloud:3306/argprograma-portfolio?
    username: onrfyq4z58coakmam7es
    password: pscale_pw_oKIoChia0oWUowito123RPTKzxb9gfzdavY7WAzonon
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: true
  servlet:
    multipart:
      max-file-size: 5MB
media:
  location: mediafiles