spring:
  datasource:
    url: jdbc:mysql://aws.connect.psdb.cloud:3306/argprograma-portfolio?
    username: g78fwr1cxag20mpu0b86
    password: pscale_pw_gdxLoo4sVQqtUCRKefwDbhTFPTW53UPpGsDY9Kuo6S5
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: true
  servlet:
    multipart:
      max-file-size: 5MB
media:
  location: mediafiles