spring:
  datasource:
    url: jdbc:mysql://bampzuvqga0bvoxhucxf-mysql.services.clever-cloud.com:3306/bampzuvqga0bvoxhucxf?
    username: upojqmywtja9cyot
    password: PMw0sUSGAOKJ6qb4qGN9
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB
media:
  location: mediafiles