spring:
  datasource:
    url: jdbc:mysql://aws.connect.psdb.cloud:3306/argprograma-portfolio?
    username: byeogi1tkg1iqekflbtk
    password: pscale_pw_9iRkakS02OkV9c2UK7sY2o5mj7CQbjvstFulT5SBne8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: true
  servlet:
    multipart:
      max-file-size: 5MB
media:
  location: mediafiles